"""Add tasks table

Revision ID: 17928f3227dd
Revises: 17928f3227ec
Create Date: 2018-01-29 17:51:08.824647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17928f3227dd'
down_revision = '17928f3227ec'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column(
            'id', sa.INTEGER(), primary_key=True
        ),
        sa.Column(
            'task_heading', sa.VARCHAR(length=64), nullable=False, index=True
        ),
        sa.Column(
            'task_description', sa.TEXT(length=1024), nullable=True
        ),
        sa.Column('due_date', sa.DATETIME, nullable=False),
        sa.Column('created_by', sa.INTEGER(), nullable=False),
        sa.Column('deleted_by', sa.INTEGER(), nullable=True),
        sa.Column('status', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DATETIME, nullable=False),
        sa.Column('deleted_at', sa.DATETIME, nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['deleted_by'], ['users.id'])
    )
    # ### end Alembic commands ###
