"""empty message

Revision ID: 17928f3227ec
Revises: 
Create Date: 2018-01-29 17:51:08.824647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17928f3227ec'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), nullable=True,
                              unique=True),
                    sa.Column('email', sa.VARCHAR(length=120), nullable=True,
                              unique=True),
                    sa.Column('password_hash', sa.VARCHAR(length=128),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
